prompt_dir: "prompts/"
explicit_model: True
think: True
memory: False
instruction_file: "abcEnv_instructions.txt"
example_file: "few-shot/abc_fs_reason_1_shot.txt"
zero_shot: False
hard_aot: False
inquiry: False
guided_instructions: False